apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-desafio-nginx
  labels: 
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment-desafio-nginx
  template:
    metadata:
      labels:
        app: deployment-desafio-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.17-alpine
          ports:
          - containerPort: 80

          volumeMounts:
          - name: htmlcontent
            mountPath: "/usr/share/nginx/html/"
            readOnly: true
        
      volumes:
        - name: htmlcontent
          configMap:
            name: index.html
            items:
            - key: index.html
              path: index.html
