steps:

- id: "Rodando docker-compose"
  name: "docker/compose"
  args: ["-f", "app-o-greeting/docker-compose.yml","up","-d","--build"]

- id: 'go_version'
  name: "gcr.io/cloud-builders/go"
  args: ["version"]
  env: ["GOPATH=."]

- id: "Gerando imagem"
  name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/go-greeting:$SHORT_SHA", "-f", "app-o-greeting/Dockerfile-cloudbuild", "."]

- id: "Pushando Imagen"
  name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/go-greeting:$SHORT_SHA"]

- id: "Unit Test"
  name: "gcr.io/cloud-builders/go"
  env: ["GOPATH=."]
  args: ["test","go-greeting"]