steps:

- id: "Rodando docker-compose"
  name: "docker/compose"
  args: ["-f", "app-o-greeting/docker-compose.yml","up","-d","--build"]

- id: 'go_version'
  name: "gcr.io/cloud-builders/go"
  args: ["version"]
  env: ["GOPATH=."]

- id: "Pull imagem"
  name: "gcr.io/cloud-builders/docker"
  args: ["pull", "https://hub.docker.com/r/dernando/go-greeting"]

#- id: "Pushando Imagen"
#  name: "gcr.io/cloud-builders/docker"
#  args: ["push", "gcr.io/$PROJECT_ID/go-greeting:$SHORT_SHA"]

#- id: "Unit Test"
#  name: "gcr.io/cloud-builders/go"
#  env: ["GOPATH=."]
#  args: ["test","go-greeting"]