steps:

- id: "Rodando docker-compose"
  name: "docker/compose"
  args: ["-f", "docker-compose.yml","up"]

- id: 'go_version'
  name: "gcr.io/cloud-builders/go"
  args: ["version"]
  env: ["GOPATH=."]


- id: "Unit Test"
  name: "gcr.io/cloud-builders/go"
  env: ["GOPATH=."]
  args: ["test","go-sum"]

  id: "Gerando imagem"
  name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/go-sum:$SHORT_SHA", "."]

- id: "Pushando Imagen"
  name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/go-sum:$SHORT_SHA"]